solids:
  upload_training_set_to_gcs:
    inputs:
      bucket_name: dagster-scratch-ccdfe1e
      file_name: training_data
  produce_training_set:
    config:
      memory_length: 1
  produce_trip_dataset:
    inputs:
      table_name:
        value: trips_staging
  produce_weather_dataset:
    solids:
      load_entire_weather_table:
        config:
          subsets:
            - time
    inputs:
      table_name:
        value: weather_staging
  train_lstm_model_and_upload_to_gcs:
    config:
      timeseries_train_test_breakpoint: 50
      model_trainig_config:
        num_epochs: 200
    inputs:
      bucket_name: dagster-scratch-ccdfe1e